In [287]:
# Import pandas; short name "pd"
import pandas as pd

# Import train_test_split.
from sklearn.model_selection import train_test_split

# Import LinearRegression class.
from sklearn.linear_model import LinearRegression

In [288]:
data = pd.read_csv("Automobile_Price_Data.csv")

In [289]:
# Returns number of observations, number of varialbes
data.shape

(205, 26)

In [290]:
data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,18920.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN

In [291]:
data.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [292]:
# Count missing values
# data.isnull().sum()

In [293]:
# Omitting missing values and modifies the data
data.dropna(inplace=True)

# Checks if there are any missing values;
# The first .any() checks each column.
# The second .any() is then applied to the Series generated by the first .any().
data.isnull().any().any()

np.False_

In [294]:
data.shape

(159, 26)

In [295]:
data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
11,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
12,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,20970.0
13,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0
18,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48.0,5100.0,47,53,5151.0
19,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,6295.0

In [296]:
data['body-style'].value_counts()

body-style
sedan          79
hatchback      56
wagon          17
hardtop         5
convertible     2
Name: count, dtype: int64

In [297]:
data["num-of-doors"].value_counts()

num-of-doors
four    95
two     64
Name: count, dtype: int64

In [298]:
# Convert current type into a pandas categorical variable and .
columns = ['make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style',
           'drive-wheels', 'engine-location', 'engine-type',
           'num-of-cylinders', 'fuel-system']

for col in columns:
    data[col] = data[col].astype(pd.CategoricalDtype())
    data[col] = data[col].cat.codes

In [299]:
data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164.0,0,1,0,0,3,1,0,99.8,...,109,4,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,0,1,0,0,3,0,0,99.4,...,136,4,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
6,1,158.0,0,1,0,0,3,1,0,105.8,...,136,4,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
8,1,158.0,0,1,1,0,3,1,0,105.8,...,131,4,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0
10,2,192.0,1,1,0,1,3,2,0,101.2,...,108,4,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
11,0,192.0,1,1,0,0,3,2,0,101.2,...,108,4,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
12,0,188.0,1,1,0,1,3,2,0,101.2,...,164,4,3.31,3.19,9.0,121.0,4250.0,21,28,20970.0
13,0,188.0,1,1,0,0,3,2,0,101.2,...,164,4,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0
18,2,121.0,2,1,0,1,2,1,0,88.4,...,61,1,2.91,3.03,9.5,48.0,5100.0,47,53,5151.0
19,1,98.0,2,1,0,1,2,1,0,94.5,...,90,1,3.03,3.11,9.6,70.0,5400.0,38,43,6295.0

In [300]:
# Checking datatypes
data.dtypes

symboling              int64
normalized-losses    float64
make                    int8
fuel-type               int8
aspiration              int8
num-of-doors            int8
body-style              int8
drive-wheels            int8
engine-location         int8
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type             int8
num-of-cylinders        int8
engine-size            int64
fuel-system             int8
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [301]:
data.describe()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.0,159.000000,...,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,0.735849,121.132075,10.113208,0.905660,0.169811,0.402516,2.654088,1.238994,0.0,98.264151,...,119.226415,2.371069,3.300126,3.236352,10.161132,95.836478,5113.836478,26.522013,32.081761,11445.729560
std,1.193086,35.651285,4.991107,0.293224,0.376653,0.491954,0.762967,0.533191,0.0,5.167416,...,30.460791,1.565262,0.267336,0.294888,3.889475,30.718583,465.754864,6.097142,6.459189,5877.856195
min,-2.000000,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,86.600000,...,61.000000,0.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,15.000000,18.000000,5118.000000
25%,0.000000,94.000000,6.000000,1.000000,0.000000,0.000000,2.000000,1.000000,0.0,94.500000,...,97.000000,1.000000,3.050000,3.105000,8.700000,69.000000,4800.000000,23.000000,28.000000,7372.000000
50%,1.000000,113.000000,10.000000,1.000000,0.000000,0.000000,3.000000,1.000000,0.0,96.900000,...,110.000000,2.000000,3.270000,3.270000,9.000000,88.000000,5200.000000,26.000000,32.000000,9233.000000
75%,2.000000,148.000000,15.000000,1.000000,0.000000,1.000000,3.000000,2.000000,0.0,100.800000,...,135.000000,4.000000,3.560000,3.410000,9.400000,114.000000,5500.000000,31.000000,37.000000,14719.500000
max,3.000000,256.000000,17.000000,1.000000,1.000000,1.000000,4.000000,2.000000,0.0,115.600000,...,258.000000,5.000000,3.940000,4.170000,23.000000,200.000000,6600.000000,49.000000,54.000000,35056.000000

In [302]:
# Select Price as the dependent/outcome variable
y = data['price']

In [303]:
# Create X, independent/predictor variables
X = data.drop(columns=['price'])

In [304]:
# Split X and y into training data (80%) and testing data (20%).
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2,
                                                    random_state=1)

In [305]:
# Create a LinearRegression model object.
model = LinearRegression()

In [306]:
# Fit/train the model using the predictor values in train_X
# and the known Price values in train_y.
model.fit(train_X, train_y)

LinearRegression()

In [307]:
# Print the intercept (constant term) of the fitted linear regression equation.
print('intercept ', model.intercept_)

intercept  -24315.81490258713

In [308]:
# Create and print a table that matches each predictor name with its estimated regression coefficient
print(pd.DataFrame({'Predictor': X.columns, 'coefficient': model.coef_}))

            Predictor   coefficient
0           symboling  2.446782e+00
1   normalized-losses -1.001683e+00
2                make -2.072627e+02
3           fuel-type  1.894847e+04
4          aspiration  3.543760e+03
5        num-of-doors -4.607793e+02
6          body-style -5.460122e+02
7        drive-wheels  9.294291e+02
8     engine-location -8.895995e-11
9          wheel-base  1.962173e+02
10             length  2.099737e+01
11              width -2.270499e+02
12             height  1.378077e+02
13        curb-weight  3.300999e+00
14        engine-type -9.302016e+01
15   num-of-cylinders -2.428287e+03
16        engine-size  1.197831e+02
17        fuel-system  2.899441e+02
18               bore -4.673147e+03
19             stroke -4.679524e+03
20  compression-ratio  1.418425e+03
21         horsepower  1.268608e+01
22           peak-rpm  1.240667e-01
23           city-mpg -4.536709e+01
24        highway-mpg  8.868151e+01

In [309]:
# Calculate R-squared on the training data; it measures how much variation in Price the model explains in the training set.
r2_train = model.score(train_X, train_y)

# Display the training R-squared value in a notebook/interactive environment.
r2_train

0.9128924444026065

In [310]:
# Calculate R-squared on the testing data to evaluate how well the model performs on data it did not train on.
r2_test = model.score(test_X, test_y)

# Display the testing R-squared value in a notebook/interactive environment.
r2_test

0.7208399476666161