In [ ]:
!pip install dmba

Requirement already satisfied: dmba in /usr/local/lib/python3.13/dist-packages (0.2.4)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from dmba) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from dmba) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from dmba) (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from dmba) (2.2.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from dmba) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from dmba) (1.16.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dmba) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->dmba) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->dmba) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dmba) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dmba) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->dmba) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib->dmba) (1.17.0)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

import dmba
from dmba import classificationSummary

# Question 1

In [ ]:
# Read the loan.csv file and store the resulting table (DataFrame) in loan_df.
loan_df = pd.read_csv('loan.csv')

# Show the first 5 rows
loan_df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
# Show observations, variables
loan_df.shape

(614, 13)

In [ ]:
# Show data type of each variable
loan_df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents           float64
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

## Cleaning and preparing the data.

Detect missing values

In [ ]:
# use to find if data has NaN, Na, or Space
loan_df.isnull().any().any()

np.True_

In [ ]:
loan_df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Drop all missing values

In [ ]:
# Remove missing values
loan_df.dropna(inplace=True)

In [ ]:
# use to find if data has NaN, Na, or Space
loan_df.isnull().any().any()

np.False_

In [ ]:
# Show observations, variables
loan_df.shape

(480, 13)

*Removed 134 observations (missing values)*

Change categorical and assign numerial values to variables

In [ ]:
loan_df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2.0,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y

In [ ]:
# Convert current type into a pandas categorical variable and a numeric category code (for example, 0, 1, 2)..
columns = ['Loan_ID', 'Gender', 'Married', 'Education', 'Self_Employed',
           'Property_Area', 'Loan_Status']

for col in columns:
    loan_df[col] = loan_df[col].astype(pd.CategoricalDtype())
    loan_df[col] = loan_df[col].cat.codes

In [ ]:
loan_df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,0,1,1,1.0,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,1,0.0,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,2,1,1,0.0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,3,1,0,0.0,0,0,6000,0.0,141.0,360.0,1.0,2,1
5,4,1,1,2.0,0,1,5417,4196.0,267.0,360.0,1.0,2,1

## 1. Split the dataset into training and test sets using the 80/20 rule

In [ ]:
# Select Loan_Status as the dependent/outcome variable that we want the model to predict.
y = loan_df['Loan_Status']

# Create X by keeping every column except Loan_Status; these remaining columns are the independent/predictor variables.
X = loan_df.drop(columns=['Loan_Status'])

# Split X and Y into training data (80%) and testing data (20%).
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

Scaler data

In [ ]:
# Initialize the StandardScaler
# Creates a StandardScaler object that will be used to standardize the predictor variables.
scaler = StandardScaler()

In [ ]:
# Scale training set
# Learns the scaling parameters from X_train and uses them to standardize the training predictors.
X_train_scaled = scaler.fit_transform(train_X)
# Converts the scaled training data from a NumPy array back into a pandas DataFrame.
X_train_scaled = pd.DataFrame(X_train_scaled)

# Scale test set
# Uses the scaling parameters learned from the training data to standardize X_test.
X_test_scaled = scaler.transform(test_X)
# Converts the scaled test data from a NumPy array back into a pandas DataFrame.
# NOTICE: Scaled only the independent variable
X_test_scaled = pd.DataFrame(X_test_scaled)

## 2. Logistic regression model

In [ ]:
# Creates a logistic regression model and stores it in the variable logit_reg.
logit_reg = LogisticRegression()

In [ ]:
# Trains the logistic regression model using the training predictors and training outcome values.
logit_reg.fit(X_train_scaled, train_y)

LogisticRegression()

In [ ]:
# Prints the intercept estimated by the logistic regression model.
print('intercept ', logit_reg.intercept_[0])

intercept  0.851070223793024

## 3. Report the following:

### a. Regression coefficients

In [ ]:
print(pd.DataFrame({'coeff': logit_reg.coef_[0]}, index=X.columns).transpose())

        Loan_ID    Gender  Married  Dependents  Education  Self_Employed  \
coeff  0.031187  0.111841  0.24067    -0.01493  -0.138611      -0.039824

       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
coeff          0.08697          -0.157437   -0.222165          -0.01916

       Credit_History  Property_Area
coeff        1.189927       0.063232

In [ ]:
# Evaluates the model on the training data by comparing actual outcomes with predicted outcomes.
classificationSummary(train_y, logit_reg.predict(X_train_scaled))

Confusion Matrix (Accuracy 0.8073)

       Prediction
Actual   0   1
     0  53  67
     1   7 257

In [ ]:
# Evaluates the model on the testing data by comparing actual outcomes with predicted outcomes.
classificationSummary(test_y, logit_reg.predict(X_test_scaled))

Confusion Matrix (Accuracy 0.8229)

       Prediction
Actual  0  1
     0 11 17
     1  0 68